name: 'Deploy Docker with Tag Action'
description: 'Triggers the update'
inputs:
  image:
    description: 'The docker image name'
    required: true
  tag:
    description: 'The docker image revision'
    required: true
  auth:
    description: 'The GH token code to use'
    required: true
  url:
    description: 'The url to post to'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
